import { Injectable, CanActivate, ExecutionContext, ForbiddenException } from '@nestjs/common';

/**
 * In production, validates that requests include the shared auth token
 * generated by the Electron main process. Prevents other local processes
 * from accessing the API while the app is running.
 *
 * In development (no BACKEND_AUTH_TOKEN set), all requests are allowed.
 */
@Injectable()
export class AuthTokenGuard implements CanActivate {
  private readonly token: string | undefined;

  constructor() {
    this.token = process.env.BACKEND_AUTH_TOKEN;
  }

  canActivate(context: ExecutionContext): boolean {
    if (!this.token) return true; // dev mode — no token required

    const request = context.switchToHttp().getRequest();
    const provided = request.headers['x-auth-token'];

    if (provided !== this.token) {
      throw new ForbiddenException('Invalid or missing auth token');
    }

    return true;
  }
}
